In [1]:
import numpy as np
from scipy import optimize
import itertools
from game_solver import Game

In [2]:
# test 1
# battle of sex
# axis0: player 0's action
# axis1: player 1's action
# axis2: payoff for player 0 and player 1
U = np.array([2,1,0,0,0,0,1,2]).reshape(2,2,-1)
print('payoff matrix:', U, sep='\n') # payoff matrix, axis i: player i's action, last axis: payoff vector
g = Game(U)
NEs = g.ne()
i = 1
for ne in NEs:
    print('NE {}: strategy profile: {}; value profile: {}'.format(i, ne[0], ne[1]))
    i+=1
    
print('\nThe first NE: ', g.ne(only_one=True))

payoff matrix:
[[[2 1]
  [0 0]]

 [[0 0]
  [1 2]]]
NE 1: strategy profile: [array([1., 0.]), array([1., 0.])]; value profile: [2. 1.]
NE 2: strategy profile: [array([0., 1.]), array([0., 1.])]; value profile: [1. 2.]
NE 3: strategy profile: [array([0.66666667, 0.33333333]), array([0.33333333, 0.66666667])]; value profile: [0.66666667 0.66666667]

The first NE:  ([array([1., 0.]), array([1., 0.])], array([2., 1.]))


In [3]:
# test 2 
# player 0 has 2 actions, player 1 has 3 actions
U = np.array([2,1,0,0,100,100,0,0,1,2,100,100]).reshape(2,3,-1)
print('payoff matrix:', U, sep='\n') # payoff matrix, axis i: player i's action, last axis: payoff vector
g = Game(U)
NEs = g.ne()
i = 1
for ne in NEs:
    print('NE {}: strategy profile: {}; value profile: {}'.format(i, ne[0], ne[1]))
    i+=1

payoff matrix:
[[[  2   1]
  [  0   0]
  [100 100]]

 [[  0   0]
  [  1   2]
  [100 100]]]
NE 1: strategy profile: [array([1., 0.]), array([0., 0., 1.])]; value profile: [100. 100.]
NE 2: strategy profile: [array([0., 1.]), array([0., 0., 1.])]; value profile: [100. 100.]


In [4]:
# test 3
# prisoner's dilemma
U = np.array([-3,-3,0,-5,-5,0,-1,-1]).reshape(2,2,-1)
print('payoff matrix:', U, sep='\n') # payoff matrix, axis i: player i's action, last axis: payoff vector
g = Game(U)
NEs = g.ne()
i = 1
for ne in NEs:
    print('NE {}: strategy profile: {}; value profile: {}'.format(i, ne[0], ne[1]))
    i+=1

payoff matrix:
[[[-3 -3]
  [ 0 -5]]

 [[-5  0]
  [-1 -1]]]
NE 1: strategy profile: [array([1., 0.]), array([1., 0.])]; value profile: [-3. -3.]


In [5]:
# test 4
# rock-paper-scissor game
# action 0: rock, action 1: paper, action 2: scissor
U = np.array([0,0,-1,1,1,-1, 1,-1,0,0,-1,1,-1,1,1,-1,0,0]).reshape(3,3,-1)
print('payoff matrix:', U, sep='\n') # payoff matrix, axis i: player i's action, last axis: payoff vector
g = Game(U)
NEs = g.ne()
i = 1
for ne in NEs:
    print('NE {}: strategy profile: {}; value profile: {}'.format(i, ne[0], ne[1]))
    i+=1

payoff matrix:
[[[ 0  0]
  [-1  1]
  [ 1 -1]]

 [[ 1 -1]
  [ 0  0]
  [-1  1]]

 [[-1  1]
  [ 1 -1]
  [ 0  0]]]
NE 1: strategy profile: [array([0.33333333, 0.33333333, 0.33333333]), array([0.33333333, 0.33333333, 0.33333333])]; value profile: [0. 0.]
